import os

MC_N_PATHS = int(os.getenv("MC_N_PATHS", "10000"))
MC_N_PATHS_WF = int(os.getenv("MC_N_PATHS_WF", "2000"))
MC_TAIL_DF = 6
HMM_STATES = 3
HMM_LOOKBACK = 730
STL_PERIOD_WEEK = 7
STL_PERIOD_MONTH = 30
BACKTEST_WINDOW = 120
WF_STRIDE = 5
STRATEGY_FEES = float(os.getenv("STRATEGY_FEES", "0.001"))
